release:
  runs-on: ubuntu-latest
  needs: build
  steps:
    - name: Download artifact from build
      uses: actions/download-artifact@v3
      with:
        name: project-release

    - name: Extract tag name
      id: extract_tag
      run: |
        # Extract tag name from refs/tags/ or refs/heads/
        ref=${{ github.ref }}
        if [[ "$ref" == refs/tags/* ]]; then
          tag_name=${ref#refs/tags/}
        else
          tag_name=${ref#refs/heads/}
        fi
        echo "tag_name=$tag_name" >> $GITHUB_ENV

    - name: Check if release already exists
      id: check_release
      run: |
        if gh release view ${{ env.tag_name }}; then
          echo "Release already exists."
          echo "release-exists=true" >> $GITHUB_ENV
        else
          echo "Release does not exist."
          echo "release-exists=false" >> $GITHUB_ENV
        fi

    - name: Create GitHub release
      if: env.release-exists == 'false'
      uses: actions/create-release@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}  # Add this line
        tag_name: ${{ env.tag_name }}
        release_name: ${{ env.tag_name }}
        body: "Release ${{ env.tag_name }}"
        draft: false
        prerelease: false

    - name: Upload release artifact
      if: env.release-exists == 'false'
      run: |
        gh release upload ${{ env.tag_name }} project-release.tar.gz

    - name: Cleanup
      run: |
        rm project-release.tar.gz
